---
name: Tidewave Web issue
description: File a bug report related to Tidewave Web

body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this bug report.

  - type: input
    id: os
    attributes:
      label: What is your operating system?
    validations:
      required: true

  - type: input
    id: ruby-version
    attributes:
      label: What is your Ruby version?
    validations:
      required: true

  - type: input
    id: rails-version
    attributes:
      label: What is your Ruby on Rails version?
    validations:
      required: true

  - type: input
    id: tidewave-version
    attributes:
      label: What is your Tidewave version?
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current behavior
      description: >
        If reporting a bug, please errors, stacktraces, and reproducing steps.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A short description on how you expected it to behave.
    validations:
      required: true
